### ISSUE TITLE
Where is the code....

### ISSUE THREAD

**Issue by mattpackwood** [dmac2535/repos#1]
Well, what are you going to post?

**Comment by mattpackwood** [comment]
Did you see there is code now?

**Comment by dmac2535** [comment]
so you dragged and drop code from java?

**Comment by mattpackwood** [comment]
Well, I copied and pasted it in this case but basically yes, you can also add repositories by having the files on your laptop and "pushing them up to create a repository" with the GitHub desktop

**Comment by mattpackwood** [comment]
Closed as no longer an issue

**Comment by dmac2535** [comment]
What’s closed?  Supository?

**Comment by mattpackwood** [comment]
The issue has been closed. Please remember that GitHub has terms that you have agreed to confirm to.
